### ISSUE TITLE
Use of `FlutterEngineGroup` instead of simply using `FlutterEngine`

### ISSUE THREAD

**Issue by saurabhkumar8112** [X-SLAYER/flutter_overlay_window#94]
Thanks for the plugin. This is not an issue but rather a question I would like to ask about the plugin

I have a question regarding how the plugin has been written. In the plugin, [here](https://github.com/X-SLAYER/flutter_overlay_window/blob/b0405c7c903c1bd674f43b34d22860edc7e1d07d/android/src/main/java/flutter/overlay/window/flutter_overlay_window/FlutterOverlayWindowPlugin.java#L127) you're using `FlutterEngineGroup` instead of spawing a `FlutterEngine`. 

Now it makes sense when multiple flutter engines are spawned and you'd like to share resources to optimize the process, but here, I don't see multiple `FlutterEngines` getting spawned, since `FlutterEngineGroup` is invoked only at the start of service.

Can you please clarify 
<img width="710" alt="image" src="https://github.com/X-SLAYER/flutter_overlay_window/assets/20687565/2e5b5576-756f-46ab-ac19-5ba24910d069">

**Comment by X-SLAYER** [comment]
Hello yes, that's true using FlutterEngine does the job but when I created the plugin it was just a strategic choice for optimization and potential scalability rather than a requirement for the current functionality. This is a forward-thinking approach that anticipates potential enhancements and use cases where multiple engines might be beneficial.
